export interface Project {
  slug: string;
  title: string;
  category: string;
  client: string;
  year: string;
  tools: string[];
  cover: string;
  gallery: string[];
  short: string;
  link?: string;
  task: string;
  process: string;
  result: string;
}

export const projects: Project[] = [
  {
    slug: "italian-pizza",
    title: "Italian Pizza",
    category: "брендинг",
    client: "Italian Pizza",
    year: "2024",
    tools: ["Figma", "Illustrator", "Photoshop"],
    cover: "/assets/italian-pizza-00.jpg",
    gallery: [
      "/assets/italian-pizza-00.jpg",
      "/assets/italian-pizza-01.jpg",
      "/assets/italian-pizza-02.jpg",
      "/assets/italian-pizza-03.jpg",
    ],
    short:
      "Создание визуального контента для SMM и графических материалов с соблюдением стандартов брендбука.",
    task: "Разработать запоминающийся бренд итальянской пиццерии.",
    process:
      "Собрали референсы по аутентичной итальянской кухне, выбрали тёплую палитру и графичную типографику. Разработали логотип, фирменные элементы и оформили меню и упаковку.",
    result:
      "Единый фирменный стиль пиццерии, который передаёт атмосферу Италии и выделяется среди конкурентов.",
  },
  {
    slug: "brozex",
    title: "BROZEX",
    category: "брендинг",
    client: "BROZEX",
    year: "2024",
    tools: ["Illustrator", "Photoshop"],
    cover: "/assets/brozex-cover.png",
    gallery: [
      "/assets/brozex-cover.png",
      "/assets/brozex-volk-01.jpg",
      "/assets/brozex-volk-02.jpg",
      "/assets/brozex-bear-01.jpg",
      "/assets/brozex-bear-02.jpg",
    ],
    short:
      "Разработка концептуального дизайна упаковки линейки сухих строительных смесей.",
    task: "Создать целостный фирменный стиль для BROZEX.",
    process:
      "Проанализировали нишу и конкурентов, разработали концепцию с динамичной графикой. Собрали логотип, палитру, типографику и деловые материалы.",
    result:
      "Готовый фирменный стиль, который сделал бренд более узнаваемым и современным.",
  },
  {
    slug: "verstka-bukleta",
    title: "Верстка буклета",
    category: "полиграфия",
    client: "Полиграфический заказ",
    year: "2023",
    tools: ["InDesign", "Illustrator"],
    cover: "/assets/buklet-02.png",
    gallery: [
      "/assets/buklet-01.jpg",
      "/assets/buklet-02.png",
      "/assets/buklet-03.jpg",
      "/assets/buklet-04.jpg",
      "/assets/buklet-06.jpg",
    ],
    short:
      "SKL | Стройкомплект: создание визуальной концепции и подготовка печатной версии каталога Britex Tyres.",
    task: "Сверстать информационный буклет компании.",
    process:
      "Разработали модульную сетку, подобрали типографику и обработали материалы. Подготовили макет к печати с соблюдением требований типографии.",
    result:
      "Чисто свёрстанный буклет, готовый к печати, с понятной структурой и единым стилем.",
  },
  {
    slug: "gaidbuk",
    title: "SKL: дизайн и верстка гайдбука",
    category: "полиграфия",
    client: "Бренд",
    year: "2023",
    tools: ["InDesign", "Illustrator", "Figma"],
    cover: "/assets/skl-cover.jpg",
    gallery: [
      "/assets/skl-cover.jpg",
      "/assets/skl-01-1.jpg",
      "/assets/skl-02-1.jpg",
      "/assets/skl-03-1.jpg",
      "/assets/skl-04.jpg",
      "/assets/skl-05.jpg",
      "/assets/skl-06.jpg",
      "/assets/skl-07.jpg",
      "/assets/skl-08.jpg",
      "/assets/skl-09.jpg",
      "/assets/skl-10.jpg",
      "/assets/skl-11.jpg",
      "/assets/skl-12.jpg",
      "/assets/skl-13.jpg",
      "/assets/skl-14.jpg",
      "/assets/skl-15.jpg",
      "/assets/skl-16.jpg",
      "/assets/skl-17.jpg",
      "/assets/skl-18.jpg",
      "/assets/skl-19.jpg",
      "/assets/skl-20.jpg",
      "/assets/skl-21.jpg",
      "/assets/skl-22.jpg",
      "/assets/skl-23.jpg",
      "/assets/skl-24.jpg",
      "/assets/skl-25.jpg",
      "/assets/skl-26.jpg",
      "/assets/skl-27.jpg",
      "/assets/skl-28.jpg",
      "/assets/skl-29.jpg",
    ],
    short:
      "Визуальная концепция и сборка стилевого руководства для SKL | Стройкомплект.",
    task: "Оформить и сверстать гайдбук по фирменному стилю.",
    process:
      "Структурировали правила бренда, спроектировали страницы и оформили примеры применения. Подготовили файл к печати.",
    result:
      "Готовый гайдбук, который помогает команде использовать фирменный стиль единообразно.",
  },
  {
    slug: "promo",
    title: "Дизайн ПРОМОакций",
    category: "реклама",
    client: "Рекламные кампании",
    year: "2023",
    tools: ["Photoshop", "Illustrator"],
    cover: "/assets/promo-cover.jpg",
    gallery: [
      "/assets/promo-cover.jpg",
      "/assets/promo-01.jpg",
      "/assets/promo-04.jpg",
      "/assets/promo-03.jpg",
      "/assets/promo-06.jpg",
    ],
    short: "Дизайн рекламных материалов для промоакций и спецпредложений.",
    task: "Разработать визуалы для серии промоакций.",
    process:
      "Создали несколько вариантов композиций, акцентируя внимание на выгоде и акции. Адаптировали макеты под разные носители.",
    result:
      "Набор ярких промоматериалов, которые повысили заметность акций и вовлечённость аудитории.",
  },
  {
    slug: "marketing-kit",
    title: "SKL: маркетинг кит",
    category: "полиграфия",
    client: "Компания",
    year: "2022",
    tools: ["InDesign", "Illustrator", "Photoshop"],
    cover: "/assets/marketing-kit-01.jpg",
    gallery: [
      "/assets/marketing-kit-01.jpg",
      "/assets/marketing-kit-03.jpg",
      "/assets/marketing-kit-05.jpg",
      "/assets/marketing-kit-06.jpg",
    ],
    short: "Концептуальный дизайн и техническая разработка.",
    task: "Создать маркетинг-кит для представления компании клиентам.",
    process:
      "Собрали информацию о компании, структурировали её и оформили в едином стиле. Подготовили электронную и печатную версии.",
    result:
      "Готовый маркетинг-кит, который помогает продавать услуги компании на переговорах.",
  },
  {
    slug: "video",
    title: "Видео ролики",
    category: "видео",
    client: "Контент-заказ",
    year: "2022",
    tools: ["Premiere Pro", "After Effects"],
    cover: "/assets/video-00-cover-2.jpg",
    gallery: ["/assets/video-00-cover-2.jpg"],
    short: "https://disk.yandex.ru/d/ZNvXrqpNCXzBxQ",
    task: "Смонтировать и оформить серию видеороликов для соцсетей.",
    process:
      "Продумали сценарии, подобрали монтаж, графику и звук. Собрали ролики в едином стиле под каждый формат площадки.",
    result:
      "Готовые видеоролики, которые увеличили охваты и вовлечённость аудитории.",
  },
  {
    slug: "shampuriko",
    title: "ШАМПУРИКО",
    category: "брендинг",
    client: "ШАМПУРИКО",
    year: "2024",
    tools: ["Figma", "Illustrator", "Photoshop"],
    cover: "/assets/shampuriko-00.jpg",
    gallery: [
      "/assets/shampuriko-00.jpg",
      "/assets/shampuriko-01.jpg",
      "/assets/shampuriko-02.jpg",
      "/assets/shampuriko-03.png",
    ],
    short:
      "Создание визуального контента для SMM и графических материалов с соблюдением стандартов брендбука.",
    task: "Разработать яркий и запоминающийся бренд для Шампурико.",
    process:
      "Изучили аудиторию и концепцию проекта, выбрали смелую палитру и динамичную графику. Оформили логотип и все носители.",
    result:
      "Узнаваемый фирменный стиль, который отражает характер бренда и привлекает клиентов.",
  },
  {
    slug: "soc-media",
    title: "Соц медиа",
    category: "контент",
    client: "Соцсети бренда",
    year: "2023",
    tools: ["Photoshop", "Illustrator", "Figma"],
    cover: "/assets/soc-media-00.jpg",
    gallery: [
      "/assets/soc-media-00.jpg",
      "/assets/soc-media-01.jpg",
      "/assets/soc-media-02.jpg",
      "/assets/soc-media-03.jpg",
      "/assets/soc-media-04.jpg",
      "/assets/soc-media-05.jpg",
      "/assets/soc-media-06.jpg",
      "/assets/soc-media-07.png",
    ],
    short: "Дизайн-контент для социальных сетей: шаблоны и публикации.",
    task: "Разработать систему визуалов для ведения соцсетей бренда.",
    process:
      "Создали шаблоны публикаций и историй в едином стиле. Подготовили наборы для разных типов контента.",
    result:
      "Цельная система контента, которая делает ленту бренда узнаваемой и аккуратной.",
  },
  {
    slug: "tematicheskoe-izdanie",
    title: "Тематическое издание",
    category: "полиграфия",
    client: "Издание",
    year: "2022",
    tools: ["InDesign", "Illustrator"],
    cover: "/assets/tematicheskoe-izdanie-01.jpg",
    gallery: [
      "/assets/tematicheskoe-izdanie-01.jpg",
      "/assets/tematicheskoe-izdanie-02.jpg",
      "/assets/tematicheskoe-izdanie-03.jpg",
      "/assets/tematicheskoe-izdanie-04.jpg",
    ],
    short: "Дизайн и вёрстка тематического печатного издания.",
    task: "Сверстать тематическое издание с красивой вёрсткой.",
    process:
      "Разработали концепцию оформления, сетку и типографику. Свёрстали статьи и разделы, подготовили макет к печати.",
    result:
      "Готовое тематическое издание с продуманной вёрсткой и единым визуальным стилем.",
  },
  {
    slug: "marketpleysy",
    title: "Маркетплейсы",
    category: "контент",
    client: "Маркетплейсы",
    year: "2023",
    tools: ["Photoshop", "Illustrator", "Figma"],
    cover: "/assets/marketpleysy-00.jpg",
    gallery: [
      "/assets/marketpleysy-00.jpg",
      "/assets/marketpleysy-01.jpg",
      "/assets/marketpleysy-02.jpg",
      "/assets/marketpleysy-03.jpg",
      "/assets/marketpleysy-04.jpg",
      "/assets/marketpleysy-05.jpg",
      "/assets/marketpleysy-06.jpg",
    ],
    short: "Оформление карточек товаров для маркетплейсов.",
    task: "Разработать дизайн карточек товаров для площадок маркетплейсов.",
    process:
      "Изучили требования площадок и поведение покупателей. Создали шаблоны инфографики и адаптировали их под разные категории товаров.",
    result:
      "Набор карточек товаров, которые повышают конверсию и аккуратно выглядят в каталоге.",
  },
  {
    slug: "tizol",
    title: "ТИЗОЛ",
    category: "реклама",
    client: "ТИЗОЛ",
    year: "2024",
    tools: ["Photoshop", "Illustrator"],
    cover: "/assets/tizol-00.png",
    gallery: [
      "/assets/tizol-00.png",
      "/assets/tizol-01.png",
      "/assets/tizol-02.png",
      "/assets/tizol-03.png",
      "/assets/tizol-04.png",
      "/assets/tizol-05.png",
      "/assets/tizol-06.png",
      "/assets/tizol-07.png",
      "/assets/tizol-08.png",
    ],
    short: "Создание рекламной кампании.",
    task: "Разработать рекламную кампанию для ТИЗОЛ.",
    process:
      "Проанализировали продукт и целевую аудиторию, разработали концепцию рекламных материалов и адаптировали макеты под разные носители.",
    result:
      "Набор рекламных материалов, которые повысили узнаваемость бренда и привлекли внимание аудитории.",
  },
  {
    slug: "tri-korovy-dva-kota",
    title: "Три коровы Два кота",
    category: "плакат",
    client: "Три коровы Два кота",
    year: "2024",
    tools: ["Illustrator", "Photoshop"],
    cover: "/assets/tri-korovy-dva-kota-00.png",
    gallery: [
      "/assets/tri-korovy-dva-kota-00.png",
      "/assets/tri-korovy-dva-kota-01.png",
      "/assets/tri-korovy-dva-kota-02.jpg",
      "/assets/tri-korovy-dva-kota-03.jpg",
      "/assets/tri-korovy-dva-kota-04.jpg",
    ],
    short: "Создание имиджевого плаката.",
    task: "Создать имиджевый плакат.",
    process:
      "Разработали концепцию и композицию имиджевого плаката, подобрали графику и оформили итоговый макет.",
    result:
      "Готовый имиджевый плакат с выразительной композицией и единым визуальным стилем.",
  },
  {
    slug: "dizayn-etiketki-i-marketpleysy",
    title: "Дизайн этикетки и маркетплейсы",
    category: "брендинг",
    client: "Дизайн этикетки и маркетплейсы",
    year: "2024",
    tools: ["Photoshop", "Illustrator", "Figma"],
    cover: "/assets/dizayn-etiketki-00.jpg",
    gallery: [
      "/assets/dizayn-etiketki-00.jpg",
      "/assets/dizayn-etiketki-01.jpg",
      "/assets/dizayn-etiketki-02.jpg",
      "/assets/dizayn-etiketki-03.jpg",
      "/assets/dizayn-etiketki-04.jpg",
      "/assets/dizayn-etiketki-05.jpg",
      "/assets/dizayn-etiketki-06.jpg",
    ],
    short: "Дизайн этикеток и оформление карточек товаров для маркетплейсов.",
    task: "Разработать дизайн этикеток и оформить карточки товаров для маркетплейсов.",
    process:
      "Разработали концепцию этикеток и инфографику карточек товаров, адаптировали макеты под требования площадок маркетплейсов.",
    result:
      "Готовые этикетки и карточки товаров, которые аккуратно выглядят в каталоге и повышают конверсию.",
  },
  {
    slug: "gid",
    title: "Gгид",
    category: "брендинг",
    client: "Gгид",
    year: "2024",
    tools: ["Illustrator", "Photoshop"],
    cover: "/assets/gid-01.png",
    gallery: [
      "/assets/gid-01.png",
      "/assets/gid-02.png",
      "/assets/gid-03.png",
      "/assets/gid-04.png",
      "/assets/gid-05.png",
      "/assets/gid-06.png",
      "/assets/gid-07.png",
      "/assets/gid-08.png",
    ],
    short: "Создание логотипа и фирменного стиля.",
    task: "Разработать логотип и фирменный стиль для Gгид.",
    process:
      "Провели исследование ниши и конкурентов, разработали концепцию логотипа и собрали элементы фирменного стиля.",
    result:
      "Целостный логотип и фирменный стиль, который делает бренд узнаваемым и современным.",
  },
  {
    slug: "razgon-akcii",
    title: "RAZGON акции",
    category: "дизайн",
    client: "RAZGON акции",
    year: "2024",
    tools: ["Photoshop", "Illustrator"],
    cover: "/assets/razgon-00.jpg",
    gallery: [
      "/assets/razgon-00.jpg",
      "/assets/razgon-01.jpg",
      "/assets/razgon-02.png",
      "/assets/razgon-03.jpg",
      "/assets/razgon-04.png",
      "/assets/razgon-05.jpg",
    ],
    short: "Ведение и оформление графической части мероприятий парков.",
    task: "Вести и оформлять графическую часть мероприятий парков.",
    process:
      "Разрабатывали и оформляли графическую составляющую мероприятий парков в едином фирменном стиле.",
    result:
      "Целостное графическое оформление мероприятий парков в фирменном стиле RAZGON.",
  },
  {
    slug: "vypusknoy",
    title: "Выпускной",
    category: "дизайн",
    client: "Выпускной",
    year: "2024",
    tools: ["Photoshop", "Illustrator"],
    cover: "/assets/vypusknoy-00.jpg",
    gallery: [
      "/assets/vypusknoy-00.jpg",
      "/assets/vypusknoy-01.jpg",
      "/assets/vypusknoy-02.jpg",
      "/assets/vypusknoy-03.jpg",
      "/assets/vypusknoy-04.jpg",
    ],
    short: "Дизайн оформления выпускного мероприятия.",
    task: "Разработать графическое оформление выпускного.",
    process:
      "Разработали концепцию и визуальные материалы оформления выпускного мероприятия в едином стиле.",
    result:
      "Целостное графическое оформление выпускного мероприятия в едином фирменном стиле.",
  },
  {
    slug: "mascot",
    title: "Маскот",
    category: "брендинг",
    client: "Маскот",
    year: "2024",
    tools: ["Illustrator", "Photoshop"],
    cover: "/assets/mascot-00.jpg",
    gallery: [
      "/assets/mascot-00.jpg",
      "/assets/mascot-01.jpg",
      "/assets/mascot-02.jpg",
      "/assets/mascot-03.jpg",
      "/assets/mascot-04.jpg",
      "/assets/mascot-05.jpg",
      "/assets/mascot-06.jpg",
    ],
    short:
      "Разработка визуального образа персонажа и всей сопутствующей графики для использования во всех медиа сферах компании.",
    task: "Разработать визуальный образ персонажа и всю сопутствующую графику.",
    process:
      "Разработали визуальный образ персонажа и сопутствующую графику для использования во всех медиа сферах компании.",
    result:
      "Готовый визуальный образ персонажа и единая сопутствующая графика для всех медиа сфер компании.",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}

export const imageDimensions: Record<
  string,
  { width: number; height: number }
> = {
  "/assets/italian-pizza-00.jpg": { width: 3317, height: 1658 },
  "/assets/italian-pizza-01.jpg": { width: 2480, height: 3508 },
  "/assets/italian-pizza-02.jpg": { width: 2480, height: 2480 },
  "/assets/italian-pizza-03.jpg": { width: 2480, height: 2959 },
  "/assets/shampuriko-00.jpg": { width: 6544, height: 4281 },
  "/assets/shampuriko-01.jpg": { width: 595, height: 842 },
  "/assets/shampuriko-02.jpg": { width: 1080, height: 1920 },
  "/assets/shampuriko-03.png": { width: 864, height: 1216 },
  "/assets/project-cover.png": { width: 1280, height: 720 },
  "/assets/promo-cover.jpg": { width: 3508, height: 2480 },
  "/assets/promo-01.jpg": { width: 5596, height: 1903 },
  "/assets/promo-03.jpg": { width: 5596, height: 1903 },
  "/assets/promo-04.jpg": { width: 4000, height: 2800 },
  "/assets/promo-06.jpg": { width: 3508, height: 2480 },
  "/assets/brozex-cover.png": { width: 1627, height: 972 },
  "/assets/brozex-volk-01.jpg": { width: 19748, height: 7972 },
  "/assets/brozex-volk-02.jpg": { width: 19748, height: 7972 },
  "/assets/brozex-bear-01.jpg": { width: 19748, height: 7972 },
  "/assets/brozex-bear-02.jpg": { width: 19748, height: 7972 },
  "/assets/buklet-01.jpg": { width: 3000, height: 2400 },
  "/assets/buklet-02.png": { width: 3141, height: 1937 },
  "/assets/buklet-03.jpg": { width: 3000, height: 2400 },
  "/assets/buklet-04.jpg": { width: 3000, height: 2400 },
  "/assets/buklet-06.jpg": { width: 3000, height: 2400 },
  "/assets/skl-cover.jpg": { width: 8000, height: 4500 },
  "/assets/skl-01-1.jpg": { width: 8000, height: 4500 },
  "/assets/skl-02-1.jpg": { width: 8000, height: 4500 },
  "/assets/skl-03-1.jpg": { width: 8000, height: 4500 },
  "/assets/skl-04.jpg": { width: 8000, height: 4500 },
  "/assets/skl-05.jpg": { width: 8000, height: 4500 },
  "/assets/skl-06.jpg": { width: 8000, height: 4500 },
  "/assets/skl-07.jpg": { width: 8000, height: 4500 },
  "/assets/skl-08.jpg": { width: 8000, height: 4500 },
  "/assets/skl-09.jpg": { width: 8000, height: 4500 },
  "/assets/skl-10.jpg": { width: 8000, height: 4500 },
  "/assets/skl-11.jpg": { width: 8000, height: 4500 },
  "/assets/skl-12.jpg": { width: 8000, height: 4500 },
  "/assets/skl-13.jpg": { width: 8000, height: 4500 },
  "/assets/skl-14.jpg": { width: 8000, height: 4500 },
  "/assets/skl-15.jpg": { width: 8000, height: 4500 },
  "/assets/skl-16.jpg": { width: 8000, height: 4500 },
  "/assets/skl-17.jpg": { width: 8000, height: 4500 },
  "/assets/skl-18.jpg": { width: 8000, height: 4500 },
  "/assets/skl-19.jpg": { width: 8000, height: 4500 },
  "/assets/skl-buklet-2.png": { width: 3141, height: 1937 },
  "/assets/skl-20.jpg": { width: 8000, height: 4500 },
  "/assets/skl-21.jpg": { width: 8000, height: 4500 },
  "/assets/skl-22.jpg": { width: 8000, height: 4500 },
  "/assets/skl-23.jpg": { width: 8000, height: 4500 },
  "/assets/skl-24.jpg": { width: 8000, height: 4500 },
  "/assets/skl-25.jpg": { width: 8000, height: 4500 },
  "/assets/skl-26.jpg": { width: 8000, height: 4500 },
  "/assets/skl-27.jpg": { width: 8000, height: 4500 },
  "/assets/skl-28.jpg": { width: 8000, height: 4500 },
  "/assets/skl-29.jpg": { width: 8000, height: 4500 },
  "/assets/marketing-kit-01.jpg": { width: 3508, height: 2480 },
  "/assets/marketing-kit-03.jpg": { width: 3508, height: 2480 },
  "/assets/marketing-kit-05.jpg": { width: 3508, height: 2480 },
  "/assets/marketing-kit-06.jpg": { width: 3508, height: 2480 },
  "/assets/video-00-cover-2.jpg": { width: 936, height: 624 },
  "/assets/soc-media-00.jpg": { width: 18755, height: 3160 },
  "/assets/soc-media-01.jpg": { width: 1080, height: 1080 },
  "/assets/soc-media-02.jpg": { width: 1080, height: 1080 },
  "/assets/soc-media-03.jpg": { width: 18755, height: 3160 },
  "/assets/soc-media-04.jpg": { width: 842, height: 534 },
  "/assets/soc-media-05.jpg": { width: 18755, height: 3160 },
  "/assets/soc-media-06.jpg": { width: 1080, height: 1080 },
  "/assets/soc-media-07.png": { width: 1080, height: 1080 },
  "/assets/tematicheskoe-izdanie-01.jpg": { width: 3508, height: 2480 },
  "/assets/tematicheskoe-izdanie-02.jpg": { width: 3508, height: 2480 },
  "/assets/tematicheskoe-izdanie-03.jpg": { width: 3508, height: 2480 },
  "/assets/tematicheskoe-izdanie-04.jpg": { width: 3508, height: 2480 },
  "/assets/marketpleysy-00.jpg": { width: 3504, height: 5604 },
  "/assets/marketpleysy-01.jpg": { width: 2454, height: 686 },
  "/assets/marketpleysy-02.jpg": { width: 1168, height: 1591 },
  "/assets/marketpleysy-03.jpg": { width: 3900, height: 3900 },
  "/assets/marketpleysy-04.jpg": { width: 2432, height: 3892 },
  "/assets/marketpleysy-05.jpg": { width: 2432, height: 4035 },
  "/assets/marketpleysy-06.jpg": { width: 2432, height: 4444 },
  "/assets/tizol-00.png": { width: 1821, height: 1380 },
  "/assets/tizol-01.png": { width: 1129, height: 1381 },
  "/assets/tizol-02.png": { width: 2436, height: 1380 },
  "/assets/tizol-03.png": { width: 915, height: 1387 },
  "/assets/tizol-04.png": { width: 2057, height: 1367 },
  "/assets/tizol-05.png": { width: 2070, height: 1380 },
  "/assets/tizol-06.png": { width: 2073, height: 1381 },
  "/assets/tizol-07.png": { width: 2073, height: 1387 },
  "/assets/tizol-08.png": { width: 2073, height: 1385 },
  "/assets/tri-korovy-dva-kota-00.png": { width: 1264, height: 1090 },
  "/assets/tri-korovy-dva-kota-01.png": { width: 2450, height: 1732 },
  "/assets/tri-korovy-dva-kota-02.jpg": { width: 2717, height: 3508 },
  "/assets/tri-korovy-dva-kota-03.jpg": { width: 2717, height: 3442 },
  "/assets/tri-korovy-dva-kota-04.jpg": { width: 2717, height: 3508 },
  "/assets/dizayn-etiketki-00.jpg": { width: 1879, height: 3861 },
  "/assets/dizayn-etiketki-01.jpg": { width: 5112, height: 1429 },
  "/assets/dizayn-etiketki-02.jpg": { width: 5112, height: 1429 },
  "/assets/dizayn-etiketki-03.jpg": { width: 5112, height: 1429 },
  "/assets/dizayn-etiketki-04.jpg": { width: 1879, height: 2872 },
  "/assets/dizayn-etiketki-05.jpg": { width: 3371, height: 2994 },
  "/assets/dizayn-etiketki-06.jpg": { width: 3371, height: 2994 },
  "/assets/gid-01.png": { width: 2090, height: 1374 },
  "/assets/gid-02.png": { width: 2656, height: 1382 },
  "/assets/gid-03.png": { width: 2091, height: 1383 },
  "/assets/gid-04.png": { width: 2099, height: 1379 },
  "/assets/gid-05.png": { width: 2091, height: 1376 },
  "/assets/gid-06.png": { width: 2498, height: 1380 },
  "/assets/gid-07.png": { width: 1849, height: 1373 },
  "/assets/gid-08.png": { width: 1207, height: 1372 },
  "/assets/razgon-00.jpg": { width: 1780, height: 2100 },
  "/assets/razgon-01.jpg": { width: 1080, height: 607 },
  "/assets/razgon-02.png": { width: 1619, height: 887 },
  "/assets/razgon-03.jpg": { width: 2728, height: 2052 },
  "/assets/razgon-04.png": { width: 2454, height: 1376 },
  "/assets/razgon-05.jpg": { width: 3000, height: 2100 },
  "/assets/mascot-00.jpg": { width: 2924, height: 2067 },
  "/assets/mascot-01.jpg": { width: 2924, height: 2068 },
  "/assets/mascot-02.jpg": { width: 2924, height: 2067 },
  "/assets/mascot-03.jpg": { width: 2924, height: 2068 },
  "/assets/mascot-04.jpg": { width: 2839, height: 1818 },
  "/assets/mascot-05.jpg": { width: 2839, height: 1818 },
  "/assets/mascot-06.jpg": { width: 3000, height: 2000 },
  "/assets/vypusknoy-00.jpg": { width: 1920, height: 1080 },
  "/assets/vypusknoy-01.jpg": { width: 2711, height: 1776 },
  "/assets/vypusknoy-02.jpg": { width: 3088, height: 2056 },
  "/assets/vypusknoy-03.jpg": { width: 1920, height: 1080 },
  "/assets/vypusknoy-04.jpg": { width: 2200, height: 1700 },
};

export const contact = {
  email: "kotvsapogah22@gmail.com",
  phone: "+7 912 274-16-14",
  phoneHref: "+79122741614",
};
